name: Setup Dhall
description: Install a Dhall version, including dhall-json, and provide the binary to run commands.
author: Craig Day
branding:
  color: blue
  icon: code

inputs:
  version:
    description: 'Version of Dhall to use. Default: `latest`'
    required: false
    default: latest
  github_token:
    description: A GitHub Token. This can help with rate limits when fetching releases.
    required: false

runs:
  using: node16
  main: src/action.js
