name: Example Workflow

on: push

jobs:
  build:
    name: Print Versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - 1.34.0
          # Updating this from latest to 1.42.0 for now as the "latest tag" (in this case 1.42.1) doesn't have the proper binaries available for download
          - 1.42.0
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dhall
        uses: ./
        with:
          version: ${{ matrix.version }}
          github_token: ${{ github.token }}

      - name: Print version
        run: |
          echo "dhall version: $(dhall version)"
          echo "dhall-json version: $(dhall-to-json --version)"
          echo "dhall-yaml version: $(dhall-to-yaml --version)"
